src/eqsans/urls.py
from django.conf.urls import patterns, url
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    url(r'^$', 'eqsans.views.reduction_home', name='eqsans_reduction_home'),
    url(r'^experiment/(?P<ipts>[\w\-]+)/$', 'eqsans.views.experiment', name='eqsans_experiment'),
    url(r'^reduction/$', 'eqsans.views.reduction_options', name='eqsans_new_reduction'),
    url(r'^reduction/(?P<reduction_id>\d+)/$', 'eqsans.views.reduction_options', name='eqsans_reduction'),
    url(r'^reduction/(?P<reduction_id>\d+)/script$', 'eqsans.views.reduction_script', name='eqsans_reduction_script'),
    url(r'^reduction/(?P<reduction_id>\d+)/submit$', 'eqsans.views.submit_job', name='eqsans_submit_job'),
    url(r'^reduction/(?P<reduction_id>\d+)/delete$', 'eqsans.views.delete_reduction', name='eqsans_delete_reduction'),
    url(r'^reduction/(?P<reduction_id>\d+)/download/py$', 'eqsans.views.py_reduction_script', name='eqsans_py_reduction_script'),
    url(r'^reduction/(?P<reduction_id>\d+)/download/xml$', 'eqsans.views.xml_reduction_script', name='eqsans_xml_reduction_script'),
    url(r'^query/(?P<job_id>[\w\-\.]+)/$', 'eqsans.views.job_details', name='eqsans_job_details'),
    url(r'^query/dummy$', 'eqsans.views.test_result'),
    url(r'^jobs/$', 'eqsans.views.reduction_jobs', name='eqsans_reduction_jobs'),
    url(r'^configuration/$', 'eqsans.views.reduction_configuration', name='eqsans_new_configuration'),
    url(r'^configuration/(?P<config_id>\d+)/$', 'eqsans.views.reduction_configuration', name='eqsans_configuration'),
    url(r'^configuration/(?P<config_id>\d+)/delete$', 'eqsans.views.reduction_configuration_delete', name='eqsans_configuration_delete'),
    url(r'^configuration/(?P<config_id>\d+)/submit$', 'eqsans.views.reduction_configuration_submit', name='eqsans_configuration_submit'),
    url(r'^configuration/query/(?P<remote_set_id>\d+)/$', 'eqsans.views.reduction_configuration_query', name='eqsans_configuration_query'),
    url(r'^configuration/iq/(?P<remote_set_id>\d+)/$', 'eqsans.views.reduction_configuration_iq', name='eqsans_configuration_iq'),
    url(r'^configuration/(?P<config_id>\d+)/(?P<reduction_id>\d+)/delete$', 'eqsans.views.reduction_configuration_job_delete', name='eqsans_configuration_job_delete'),

)

src/reduction_service/urls.py
from django.conf.urls import patterns, include, url
from django.conf import settings
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    url(r'^$', 'reduction_service.views.home', name='home'),
    url(r'^eqsans/', include('eqsans.urls')),
    url(r'^remote/', include('remote.urls')),
    url(r'^catalog/', include('catalog.urls')),
    url(r'^plotting/', include('plotting.urls')),
    url(r'^users/', include('users.urls')),
    url(r'^database/doc/', include('django.contrib.admindocs.urls')),
    url(r'^database/', include(admin.site.urls)),
)

if settings.DEBUG_TOOLBAR:
    import debug_toolbar
    urlpatterns += patterns('',
        url(r'^__debug__/', include(debug_toolbar.urls)),
    )

src/users/urls.py
from django.conf.urls import patterns, include, url

urlpatterns = patterns('',
    url(r'^login$', 'users.views.perform_login'),
    url(r'^logout$', 'users.views.perform_logout'),
)

src/eqsans/forms.py
"""
    Forms for EQSANS reduction
    
    @author: M. Doucet, Oak Ridge National Laboratory
    @copyright: 2014 Oak Ridge National Laboratory
"""
from django import forms
from django.shortcuts import get_object_or_404
from models import ReductionProcess, Instrument, Experiment, ReductionConfiguration
import time
import sys
import json
import logging
import copy
logger = logging.getLogger('eqsans.forms')

def _process_experiment(reduction_obj, expt_string):
    """
        Process the experiment string of a form and find/create
        the appropriate Experiment object
        @param reduction_obj: ReductionProcess or ReductionConfiguration object
        @param expt_string: string taken from the reduction form
    """
    # Find experiment
    uncategorized_expt = Experiment.objects.get_uncategorized('eqsans')
    expts = expt_string.split(',')
    for item in expts:
        # Experiments have unique names of no more than 24 characters
        expt_objs = Experiment.objects.filter(name=item.upper().strip()[:24])
        if len(expt_objs)>0:
            if expt_objs[0] not in reduction_obj.experiments.all():
                reduction_obj.experiments.add(expt_objs[0])
        else:
            expt_obj = Experiment(name=item.upper().strip()[:24])
            expt_obj.save()
            reduction_obj.experiments.add(expt_obj)
    
    # Clean up the uncategorized experiment object if we found
    # at least one suitable experiment to associate with this reduction
    if len(expts)>0:
        if uncategorized_expt in reduction_obj.experiments.all():
            try:
                reduction_obj.experiments.remove(uncategorized_expt)
            except:
                logger.error("Could not remote uncategorized expt: %s" % sys.exc_value)
    else:
        reduction_obj.experiments.add(uncategorized_expt)


class ReductionConfigurationForm(forms.Form):
    """
        Configuration form for EQSANS reduction
    """
    # General information
    reduction_name = forms.CharField(required=False, initial='Configuration')
    experiment = forms.CharField(required=True, initial='uncategorized')
    absolute_scale_factor = forms.FloatField(required=False, initial=1.0)
    dark_current_run = forms.CharField(required=False, initial='')
    sample_aperture_diameter = forms.FloatField(required=False, initial=10.0)
    beam_radius = forms.FloatField(required=False, initial=3.0, widget=forms.HiddenInput)
    fit_frames_together = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)
    theta_dependent_correction = forms.BooleanField(required=False, initial=True, widget=forms.HiddenInput)
    mask_file = forms.CharField(required=False, initial='')
    
    # Beam center
    direct_beam_run = forms.CharField(required=True)
    
    # Sensitivity
    sensitivity_file = forms.CharField(required=False, initial='')
    sensitivity_min = forms.FloatField(required=False, initial=0.4)
    sensitivity_max = forms.FloatField(required=False, initial=2.0)
    
    # Data
    sample_thickness = forms.FloatField(required=False, initial=1.0)
    transmission_empty = forms.CharField(required=True)

    @classmethod
    def data_from_db(cls, user, reduction_config):
        """
            Return a dictionary that we can use to populate the initial
            contents of a form
            @param user: User object
            @param reduction_config: ReductionConfiguration object
        """
        data = reduction_config.get_data_dict()
        # Ensure all the fields are there
        for f in cls.base_fields:
            if not f in data:
                data[f]=cls.base_fields[f].initial
        expt_list = reduction_config.experiments.all()
        data['experiment'] = ', '.join([str(e.name) for e in expt_list if len(str(e.name))>0])
        return data

    def to_db(self, user, config_id=None):
        """
            Save a configuration to the database
            @param user: User object
            @param config_id: PK of the config object to update (None for creation)
        """
        eqsans = Instrument.objects.get(name='eqsans')
        # Find or create a reduction process entry and update it
        if config_id is not None:
            reduction_config = get_object_or_404(ReductionConfiguration, pk=config_id, owner=user)
            reduction_config.name = self.cleaned_data['reduction_name']
        else:
            reduction_config = ReductionConfiguration(owner=user,
                                                      instrument=eqsans,
                                                      name=self.cleaned_data['reduction_name'])
            reduction_config.save()
        
        # Find experiment
        _process_experiment(reduction_config, self.cleaned_data['experiment'])
                
        # Set the parameters associated with the reduction process entry
        try:
            property_dict = copy.deepcopy(self.cleaned_data)
            # Make sure we have a background transmission empty
            property_dict['background_transmission_empty']=property_dict['transmission_empty']
            # This configuration requires that we fit the beam center
            property_dict['fit_direct_beam'] = True
            # Set the sensitivity calculation flag as needed
            if len(property_dict['sensitivity_file'])>0:
                property_dict['perform_sensitivity']=True
            properties = json.dumps(property_dict)
            reduction_config.properties = properties
            reduction_config.save()
        except:
            logger.error("Could not process reduction properties: %s" % sys.exc_value)
        
        return reduction_config.pk


class ReductionOptions(forms.Form):
    """
        Reduction parameter form
    """
    # Reduction name
    reduction_name = forms.CharField(required=False)
    reduction_id = forms.IntegerField(required=False, widget=forms.HiddenInput)
    expt_id = forms.IntegerField(required=False, widget=forms.HiddenInput)
    experiment = forms.CharField(required=False, initial='uncategorized')
    nickname = forms.CharField(required=False, initial='')
    # General options
    absolute_scale_factor = forms.FloatField(required=False, initial=1.0)
    dark_current_run = forms.CharField(required=False, initial='')
    sample_aperture_diameter = forms.FloatField(required=False, initial=10.0)
    mask_file = forms.CharField(required=False, initial='')
    
    # Beam center
    beam_center_x = forms.FloatField(required=False, initial=96.0)
    beam_center_y = forms.FloatField(required=False, initial=128.0)
    fit_direct_beam = forms.BooleanField(required=False, initial=False,
                                         help_text='Select to fit the beam center')
    direct_beam_run = forms.CharField(required=False, initial='')
    
    # Sensitivity
    perform_sensitivity = forms.BooleanField(required=False, initial=False,
                                             label='Perform sensitivity correction',
                                             help_text='Select to enable sensitivity correction')
    sensitivity_file = forms.CharField(required=False, initial='')
    sensitivity_min = forms.FloatField(required=False, initial=0.4)
    sensitivity_max = forms.FloatField(required=False, initial=2.0)
    
    # Data
    data_file = forms.CharField(required=True)
    sample_thickness = forms.FloatField(required=False, initial=1.0)
    transmission_sample = forms.CharField(required=True)
    transmission_empty = forms.CharField(required=False)
    beam_radius = forms.FloatField(required=False, initial=3.0, widget=forms.HiddenInput)
    fit_frames_together = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)
    theta_dependent_correction = forms.BooleanField(required=False, initial=True, widget=forms.HiddenInput)
    
    # Background
    subtract_background = forms.BooleanField(required=False, initial=False,
                                             help_text='Select to enable background subtraction')
    background_file = forms.CharField(required=False, initial='')
    background_transmission_sample = forms.CharField(label='Transmission sample', required=False, initial='')
    background_transmission_empty = forms.CharField(label='Transmission empty', required=False, initial='')
    
    @classmethod
    def as_xml(cls, data):
        """
            Create XML from the current data.
            @param data: dictionary of reduction properties
        """
        xml  = "<Reduction>\n"
        xml += "<instrument_name>EQSANS</instrument_name>\n"
        xml += "<timestamp>%s</timestamp>\n" % time.ctime()
        xml += "<Instrument>\n"
        xml += "  <name>EQSANS</name>\n"
        xml += "  <solid_angle_corr>True</solid_angle_corr>\n"
        dark_corr = data['dark_current_run'] and str(len(data['dark_current_run'])>0)
        xml += "  <dark_current_corr>%s</dark_current_corr>\n" % dark_corr
        xml += "  <dark_current_data>%s</dark_current_data>\n" % data['dark_current_run']

        xml += "  <n_q_bins>100</n_q_bins>\n" # TODO
        xml += "  <log_binning>False</log_binning>\n"  #TODO

        xml += "  <normalization>2</normalization>\n" # 2 is monitor normalization
        xml += "  <UseDataDirectory>False</UseDataDirectory>\n"
        xml += "  <OutputDirectory></OutputDirectory>\n" # TODO
        xml += "</Instrument>\n"
        
        xml += "<AbsScale>\n"
        xml += "  <scaling_factor>%s</scaling_factor>\n" % data['absolute_scale_factor']
        xml += "  <calculate_scale>False</calculate_scale>\n"
        xml += "</AbsScale>\n"

        # TOF cutoff and correction
        xml += "<TOFcorr>\n"
        xml += "  <use_config_cutoff>True</use_config_cutoff>\n"
        xml += "  <perform_flight_path_corr>True</perform_flight_path_corr>\n"
        xml += "</TOFcorr>\n"
        
        # Mask
        if 'mask_file' in data and len(data['mask_file'])>0:

templates/eqsans/eqsans_base.html
{% extends "base.html" %}

{% block page_specific_tools %}
      <div class="tool_area">
        <b>Catalog</b><br>
        <ul>
          <li><a href="{% url 'catalog_experiments' 'eqsans'%}" title="See all experiments for this instrument">see experiments</a></li>
          {% spaceless %}
          {% if ipts_number and is_categorized %}
          <li><a href="{% url 'catalog_runs' 'eqsans' ipts_number%}" title="See all runs for this experiment">see {{ ipts_number }} runs</a></li>
          {% endif %}
          {% for expt in expt_list %}
            {% if not expt.is_uncategorized and expt.name|length > 0 %}
            <li><a href="{% url 'catalog_runs' 'eqsans' expt%}" title="See all runs for this experiment">see {{ expt }} runs</a></li>
            {% endif %}
          {% endfor %}
          {% endspaceless %}
        </ul>
      </div>
      <div class="tool_area">
        <b>Reduction</b><br>
        <ul>
          <li><a href="{% url 'eqsans_reduction_home' %}" title="Go to reduction home for this instrument">reduction home</a></li>
          <li><a href="{% url 'eqsans_new_configuration' %}" title="Start a new configuration to use with multiple reductions">new configuration</a></li>
          <li><a href="{% url 'eqsans_new_reduction' %}" title="Start a new single reduction">new reduction</a></li>
          {% if reduction_id %}
          <li><a href="{% url 'eqsans_reduction_script' reduction_id %}" title="See reduction script">see script</a></li>
          <li><a href="{% url 'eqsans_py_reduction_script' reduction_id %}" title="Download python script">download python</a></li>
          <li><a href="{% url 'eqsans_xml_reduction_script' reduction_id %}" title="Download Mantid xml file">download xml</a></li>
          {% endif %}
        </ul>
      </div>
      <div class="tool_area">
        <b>Remote jobs</b><br>
        <ul>
          <li><a href="{% url 'eqsans_reduction_jobs'%}" title="See remote jobs">see all jobs</a></li>
          {% if config_id %}
          <li><a href="{% url 'eqsans_configuration_submit' config_id %}" title="Submit jobs for this configuration">submit jobs</a></li>
          {% if existing_job_sets and existing_job_sets|length > 0 %}
          {% for job in existing_job_sets %}
          <li><a href="{% url 'eqsans_configuration_query' job.id %}" title="See job details">job set {{ job.id }}</a></li>
          {% endfor %}
          {% endif %}
          {% endif %}
          {% if reduction_id %}
          <li><a href="{% url 'eqsans_submit_job' reduction_id %}" title="Submit this reduction job">submit this job</a></li>
          {% if existing_jobs and existing_jobs|length > 0 %}
          {% for job in existing_jobs %}
          <li><a href="{% url 'eqsans_job_details' job.remote_id %}" title="See job details">job {{ job.remote_id }}</a></li>
          {% endfor %}
          {% endif %}
          {% endif %}
          {% if trans_id %}
          <li><a href="{% url 'remote_stop_transaction' trans_id %}?back_url={% url 'eqsans_reduction_jobs'%}" title="Delete this job and all the files associated with this transaction">delete this job</a></li>
          {% endif %}
        </ul>
      </div>
{% endblock %}

templates/eqsans/reduction_home.html
{% extends "eqsans/eqsans_base.html" %}


{% block content %}
<h2>List of experiments for which you have set up reductions.</h2>
<p>
{% if experiments %}
<p>
<table class="reduction_table">
  <thead>
    <tr>
      <th>Experiment</th><th>First reduced on</th>
    </tr>
  </thead>
  <tbody>
  {% for e in experiments %}
    <tr class="{% if forloop.counter|divisibleby:2 %}even{% else %}odd{% endif %}">
        <td><a href="{% url 'eqsans_experiment' e.name %}" >{{ e.name }}</a></td>
        <td><div class='subtitle_black'>{{ e.created_on }}</div></td>
    </tr>
  {% endfor %}
  </tbody>
</table>
{% endif %}
<p>

{% endblock %}

templates/eqsans/reduction_options.html
{% extends "eqsans/eqsans_base.html" %}
{% block header %}
<script>
    var hide_beam_center = !{{ options_form.fit_direct_beam.value|lower }};
    function toggle_beam_center() {
        if (hide_beam_center) {
            $("#id_direct_beam_run").fadeOut(10);
            $("#th_direct_beam_run").fadeOut(10);
            $("#id_beam_center_x").fadeIn(10);
            $("#id_beam_center_y").fadeIn(10);
            $("#th_beam_center_x").fadeIn(10);
            $("#th_beam_center_y").fadeIn(10);
            $("#unit_beam_center_x").fadeIn(10);
            $("#unit_beam_center_y").fadeIn(10);
        } else {
            $("#id_direct_beam_run").fadeIn(10);
            $("#th_direct_beam_run").fadeIn(10);
            $("#id_beam_center_x").fadeOut(10);
            $("#id_beam_center_y").fadeOut(10);
            $("#th_beam_center_x").fadeOut(10);
            $("#th_beam_center_y").fadeOut(10);
            $("#unit_beam_center_x").fadeOut(10);
            $("#unit_beam_center_y").fadeOut(10);
        }
        hide_beam_center = !hide_beam_center;
    }
    
    var hide_sensitivity = !{{ options_form.perform_sensitivity.value|lower }};
    function toggle_sensitivity() {
        if (hide_sensitivity) {
            $("#th_sensitivity_file").fadeOut(10);
            $("#th_sensitivity_min").fadeOut(10);
            $("#th_sensitivity_max").fadeOut(10);
            $("#id_sensitivity_file").fadeOut(10);
            $("#id_sensitivity_min").fadeOut(10);
            $("#id_sensitivity_max").fadeOut(10);
        } else {
            $("#th_sensitivity_file").fadeIn(10);
            $("#th_sensitivity_min").fadeIn(10);
            $("#th_sensitivity_max").fadeIn(10);
            $("#id_sensitivity_file").fadeIn(10);
            $("#id_sensitivity_min").fadeIn(10);
            $("#id_sensitivity_max").fadeIn(10);
        }
        hide_sensitivity = !hide_sensitivity;
    }

    var hide_background = !{{ options_form.subtract_background.value|lower }};
    function toggle_background() {
        if (hide_background) {
            $("#th_background_file").fadeOut(10);
            $("#th_background_transmission_sample").fadeOut(10);
            $("#th_background_transmission_empty").fadeOut(10);
            $("#id_background_file").fadeOut(10);
            $("#id_background_transmission_sample").fadeOut(10);
            $("#id_background_transmission_empty").fadeOut(10);
            $("#background_transmission_empty_info").fadeOut(10);
        } else {
            $("#th_background_file").fadeIn(10);
            $("#th_background_transmission_sample").fadeIn(10);
            $("#th_background_transmission_empty").fadeIn(10);
            $("#id_background_file").fadeIn(10);
            $("#id_background_transmission_sample").fadeIn(10);
            $("#id_background_transmission_empty").fadeIn(10);
            $("#background_transmission_empty_info").fadeIn(10);
        }
        hide_background = !hide_background;
    }

    function get_icat_info(run_number, element_id) {
        $.ajax({ url: "{{ icat_url }}"+run_number+"/", 
                 success: function(data) {
                        $('#'+element_id).replaceWith("<span class='subtitle' id='"+element_id+"'>"+data.title+"</span>");
                      }
                 , dataType: "json", timeout: 30000, cache: true});
    }
    
    $(function() {
      $("#tabs").tabs({ active: 2 });
      $("#submit_reduction_button").button();
      $("#execute_job_button").button();
    });
</script>
{% endblock %}

{% block content %}
<h2>Reduction parameters</h2>
<form action="" method="POST">{% csrf_token %}
  <div class='tiled_area'><div class='flexible tile'>
    <table class='property_table'>
      <tr><th>{{ options_form.reduction_name.label_tag }}</th><td class='long_input'>{{ options_form.reduction_name }}</td></tr>
      <tr><th title='Enter an experiment identifier or IPTS number'>{{ options_form.experiment.label_tag }}</th><td class='long_input'>{{ options_form.experiment }}</td></tr>
    </table>
  </div></div>
  <p>
  <div id="tabs">
    <ul>
      <li><a href="#tabs-1">Basic options</a></li>
      <li><a href="#tabs-2">Detector</a></li>
      <li><a href="#tabs-3">Data</a></li>
    </ul>
    <div id="tabs-1">
      <table cellspacing="0" class="property_table">
        <tbody>
          <tr><th>{{ options_form.absolute_scale_factor.label_tag }}</th><td>{{ options_form.absolute_scale_factor.errors }}{{ options_form.absolute_scale_factor }}</td></tr>
          <tr><th>{{ options_form.dark_current_run.label_tag }}</th><td>{{ options_form.dark_current_run.errors }}{{ options_form.dark_current_run }} <span id='dark_current_run_info'></span></td></tr>
          <tr><th>{{ options_form.sample_aperture_diameter.label_tag }}</th><td>{{ options_form.sample_aperture_diameter.errors }}{{ options_form.sample_aperture_diameter }} [mm]</td></tr>
          <tr><th>{{ options_form.mask_file.label_tag }}</th><td>{{ options_form.mask_file.errors }}{{ options_form.mask_file }}</td></tr>
        </tbody>
      </table>
    </div>
    <div id="tabs-2">
      <h3>Beam center position:</h3><br>
      <table cellspacing="0" class="property_table">
        <tbody>
          <tr><th>{{ options_form.fit_direct_beam.label_tag }}</th><td><a title='{{ options_form.fit_direct_beam.help_text }}' href='javascript:void(0);' onClick="toggle_beam_center();">{{ options_form.fit_direct_beam }}</a></td></tr>
          <tr><th id="th_direct_beam_run">{{ options_form.direct_beam_run.label_tag }}</th><td>{{ options_form.direct_beam_run.errors }}{{ options_form.direct_beam_run }} <span id='direct_beam_run_info'></span></td></tr>
          <tr><th id="th_beam_center_x">{{ options_form.beam_center_x.label_tag }}</th><td>{{ options_form.beam_center_x.errors }}{{ options_form.beam_center_x }} <span id="unit_beam_center_x">[pixel]</span></td></tr>
          <tr><th id="th_beam_center_y">{{ options_form.beam_center_y.label_tag }}</th><td>{{ options_form.beam_center_y.errors }}{{ options_form.beam_center_y }} <span id="unit_beam_center_y">[pixel]</span></td></tr>
        </tbody>
      </table>

      <hr>
      <h3>Sensitivity correction:</h3><br>
      <table cellspacing="0" class="property_table">
        <tbody>
          <tr><th>{{ options_form.perform_sensitivity.label_tag }}</th><td><a title='{{ options_form.perform_sensitivity.help_text }}' href='javascript:void(0);' onClick="toggle_sensitivity();">{{ options_form.perform_sensitivity }}</a></td></tr>
          <tr><th id="th_sensitivity_file">{{ options_form.sensitivity_file.label_tag }}</th><td>{{ options_form.sensitivity_file.errors }}{{ options_form.sensitivity_file }} <span id='sensitivity_file_info'></span></td></tr>
          <tr><th id="th_sensitivity_min">{{ options_form.sensitivity_min.label_tag }}</th><td>{{ options_form.sensitivity_min.errors }}{{ options_form.sensitivity_min }}</td></tr>
          <tr><th id="th_sensitivity_max">{{ options_form.sensitivity_max.label_tag }}</th><td>{{ options_form.sensitivity_max.errors }}{{ options_form.sensitivity_max }}</td></tr>
        </tbody>
      </table>
    </div>

    <div id="tabs-3">
      <h3>Sample:</h3><br>
      <table cellspacing="0" class="property_table">
        <tbody>
          <tr><th>{{ options_form.data_file.label_tag }}</th><td>{{ options_form.data_file.errors }}{{ options_form.data_file }} <span id='data_file_info'></span></td></tr>
          <tr><th>{{ options_form.sample_thickness.label_tag }}</th><td>{{ options_form.sample_thickness.errors }}{{ options_form.sample_thickness }} [cm]</td></tr>
          <tr><th>{{ options_form.transmission_sample.label_tag }}</th><td>{{ options_form.transmission_sample.errors }}{{ options_form.transmission_sample }} <span id='transmission_sample_info'></span></td></tr>
          <tr><th>{{ options_form.transmission_empty.label_tag }}</th><td>{{ options_form.transmission_empty.errors }}{{ options_form.transmission_empty }} <span id='transmission_empty_info'></span></td></tr>
        </tbody>
      </table>
      {{ options_form.beam_radius }} {{ options_form.fit_frames_together }} {{ options_form.theta_dependent_correction }}
      <hr>
      <h3>Background:</h3><br>
      <table cellspacing="0" class="property_table">
        <tbody>
          <tr><th>{{ options_form.subtract_background.label_tag }}</th><td><a title='{{ options_form.subtract_background.help_text }}' href='javascript:void(0);' onClick="toggle_background();">{{ options_form.subtract_background }}</a></td></tr>
          <tr><th id="th_background_file">{{ options_form.background_file.label_tag }}</th><td>{{ options_form.background_file.errors }}{{ options_form.background_file }} <span id='background_file_info'></span></td></tr>
          <tr><th id="th_background_transmission_sample">{{ options_form.background_transmission_sample.label_tag }}</th><td>{{ options_form.background_transmission_sample.errors }}{{ options_form.background_transmission_sample }} <span id='background_transmission_sample_info'></span></td></tr>
          <tr><th id="th_background_transmission_empty">{{ options_form.background_transmission_empty.label_tag }}</th><td>{{ options_form.background_transmission_empty.errors }}{{ options_form.background_transmission_empty }} <span id='background_transmission_empty_info'></span></td></tr>
        </tbody>
      </table>
    </div>
  </div>
  <p>
    <input title="Click to apply your changes to this reduction" id="submit_reduction_button" type="submit" value="update"/>
    {% if reduction_id %}<input title="Click to submit this reduction for execution" id="execute_job_button" type="button" value="submit" onclick='window.location.href = "{% url 'eqsans_submit_job' reduction_id %}"'/>{% endif %}
  </p>
</form>

<script type="text/javascript">

$(document).ready(function() {
    get_icat_info('{{ options_form.data_file.value }}','data_file_info');
    get_icat_info('{{ options_form.transmission_sample.value }}','transmission_sample_info');
    get_icat_info('{{ options_form.transmission_empty.value }}','transmission_empty_info');
    get_icat_info('{{ options_form.sensitivity_file.value }}','sensitivity_file_info');
    get_icat_info('{{ options_form.direct_beam_run.value }}','direct_beam_run_info');
    get_icat_info('{{ options_form.dark_current_run.value }}','dark_current_run_info');
    toggle_beam_center();
    toggle_sensitivity();
    toggle_background();
    if ($('#subtract_background').is(':checked')) {
        get_icat_info('{{ options_form.background_file.value }}','background_file_info');
        get_icat_info('{{ options_form.background_transmission_sample.value }}','background_transmission_sample_info');
        get_icat_info('{{ options_form.background_transmission_empty.value }}','background_transmission_empty_info');
    }
    $(window).keydown(function(event){
      if(event.keyCode == 13) {
        event.preventDefault();
        return false;
      }
    });
    });
</script>
{% endblock %}